In [1]:
%matplotlib inline
import matplotlib.pyplot as pl
import pandas as pd
import statsmodels.api as sm
import seaborn

df = pd.read_csv("dataset/copacabana.csv", sep=";")

ImportError: No module named 'statsmodels'

In [15]:
df.describe()

,Posicao,Quartos,Vagas,DistIpanema,DistPraia,DistFavela,RendaMedia,RendaMovel,RendaMovelRua,Vu2009,Mes,Idade,Tipologia,AreaConstruida,VAL_UNIT,X,Y
count,1675.000000,1675.000000,1675.000000,1675.000000,1675.000000,1675.000000,1675.000000,1675.000000,1675.000000,1675.000000,1675.000000,1675.000000,1675.000000,1675.000000,1675.000000,1675.000000,1675.000000
mean,0.601791,1.767510,0.330842,2112.444179,353.662687,405.623284,1232577.487761,1214159.103284,1223368.549254,2249.367164,646.903881,50.036442,1.071642,78.880597,8084.660896,685980.624667,7458578.793014
std,0.489675,1.142523,0.576720,909.254397,241.712897,215.175421,245447.448516,350290.220006,271898.372733,518.861409,204.075055,11.611873,0.345134,59.504466,3742.027190,630.889668,756.498966
min,0.000000,0.010000,0.010000,337.000000,31.000000,15.000000,498256.000000,442668.000000,498256.000000,780.000000,360.000000,0.010000,1.000000,15.000000,2037.000000,685024.810000,7456842.012000
25%,0.000000,1.000000,0.010000,1414.000000,179.000000,226.500000,1083455.000000,1000877.000000,1044083.500000,2000.000000,445.000000,44.000000,1.000000,38.000000,5000.000000,685472.150000,7458048.050000
50%,1.000000,2.000000,0.010000,2259.000000,318.000000,403.000000,1165764.000000,1175438.000000,1187842.000000,2200.000000,567.000000,53.000000,1.000000,63.000000,7212.000000,685792.470000,7458775.800000
75%,1.000000,3.000000,1.000000,2805.500000,462.500000,576.500000,1395924.000000,1398392.000000,1360871.500000,2500.000000,862.000000,57.000000,1.000000,98.500000,10606.000000,686490.585000,7459227.830000
max,1.000000,6.000000,4.000000,3611.000000,1242.000000,851.000000,2068724.000000,2922751.000000,2223676.000000,4100.000000,940.000000,75.000000,3.000000,668.000000,24490.000000,687253.719900,7459698.140000

In [16]:
Y = df["VAL_UNIT"]

In [17]:
X = df[["Quartos", "Vagas", "DistIpanema", "DistPraia", "DistFavela", "RendaMedia", "Mes", "Idade"]]

In [18]:
Y

0      4379
1      6479
2     12414
3     11250
4     13382
5     11618
6      6505
7      6410
8     14545
9     11111
10    19500
11    13636
12    20500
13    10135
14    10081
...
1660     7773
1661    15909
1662     5726
1663    13750
1664     5556
1665    13462
1666     7500
1667     8365
1668     2716
1669     8533
1670     4210
1671     4232
1672     6316
1673     6785
1674     6771
Name: VAL_UNIT, Length: 1675, dtype: int64

In [19]:
X

,Quartos,Vagas,DistIpanema,DistPraia,DistFavela,RendaMedia,Mes,Idade
0,3.00,0.01,1144,311,146,969501,509,37.00
1,2.00,0.01,2456,502,254,1472861,484,30.00
2,2.00,0.01,2448,772,229,1803724,920,44.00
3,2.00,0.01,1615,428,310,1124331,930,43.00
4,2.00,1.00,2358,586,287,1165764,918,42.00
5,2.00,1.00,2358,586,287,1165764,825,42.00
6,3.00,0.01,2537,758,115,994427,864,43.00
7,0.01,0.01,555,332,306,1140573,554,40.00
8,1.00,0.01,555,332,306,1140573,830,43.00
9,1.00,0.01,555,332,306,1140573,940,43.00
10,1.00,0.01,555,332,306,1140573,918,43.00
11,0.01,0.01,555,332,306,1140573,918,43.00
12,0.01,0.01,555,332,306,1140573,864,43.00
13,3.00,1.00,2498,716,148,1281444,830,43.00
14,2.00,0.01,2498,716,148,1281444,830,43.00
15,2.00,0.01,2498,716,148,1281444,920,43.00
16,2.00,1.00,2498,716,148,1281444,360,40.00
17,2.00,0.01,2835,330,629,1124331,385,40.00
18,2.00,2.00,2835,330,629,1124331,918,43.00
19,3.00,0.01,1987,494,510,1369604,920,44.00
20,0.01,0.01,2057,307,621,1395924,792,43.00
21,0.01,0.01,2057,307,621,1395924,801,43.00
22,1.00,0.01,2057,307,621,1395924,573,41.00
23,1.00,0.01,2057,307,621,1395924,425,41.00
24,0.01,0.01,2057,307,621,1395924,801,43.00
25,1.00,0.01,2057,307,621,1395924,405,41.00
26,3.00,0.01,3207,145,467,1083455,509,53.00
27,2.00,0.01,474,212,492,1308645,554,38.00
28,2.00,0.01,1191,564,125,2068724,445,40.00
29,2.00,0.01,2536,817,156,1165764,360,40.00
...,...,...,...,...,...,...,...,...
1645,1.00,0.01,1565,702,44,1286868,904,75.00
1646,2.00,0.01,1565,702,44,1286868,904,75.00
1647,1.00,1.00,1565,702,44,1286868,920,75.00
1648,3.00,0.01,1565,702,44,1286868,904,75.00
1649,1.00,1.00,1565,702,44,1286868,864,75.00
1650,2.00,2.00,2650,419,381,1357174,842,17.00
1651,2.00,2.00,2650,419,381,1357174,554,14.00
1652,2.00,2.00,2650,419,381,1357174,484,14.00
1653,1.00,0.01,791,445,47,1056413,825,17.00
1654,4.00,3.00,2442,894,189,1783469,920,12.00
1655,2.00,2.00,2853,530,436,1915512,930,12.00
1656,1.00,0.01,1669,69,693,1447740,385,7.00
1657,1.00,0.01,1669,69,693,1447740,405,7.00
1658,1.00,0.01,1669,69,693,1447740,573,7.00
1659,1.00,0.01,1669,69,693,1447740,573,7.00
1660,1.00,0.01,1669,69,693,1447740,445,7.00
1661,1.00,0.01,1669,69,693,1447740,862,10.00
1662,3.00,2.00,2564,949,183,1803724,425,7.00
1663,2.00,2.00,2391,856,182,1395924,792,9.00
1664,1.00,0.01,1163,377,143,969501,509,6.00
1665,1.00,0.01,1163,377,143,969501,862,9.00
1666,2.00,0.01,1163,377,143,969501,445,6.00
1667,1.00,1.00,1163,377,143,969501,573,6.00
1668,2.00,2.00,604,542,106,1056413,360,5.00
1669,2.00,2.00,2866,562,416,1915512,554,2.00
1670,2.00,2.00,2866,562,416,1915512,360,2.00
1671,2.00,2.00,2488,1030,106,1395924,509,0.01
1672,2.00,2.00,2488,1030,106,1395924,509,0.01
1673,2.00,2.00,2488,1030,106,1395924,445,0.01
1674,2.00,2.00,2488,1030,106,1395924,445,0.01

In [20]:
X = sm.add_constant(X)

In [21]:
X

,const,Quartos,Vagas,DistIpanema,DistPraia,DistFavela,RendaMedia,Mes,Idade
0,1,3.00,0.01,1144,311,146,969501,509,37.00
1,1,2.00,0.01,2456,502,254,1472861,484,30.00
2,1,2.00,0.01,2448,772,229,1803724,920,44.00
3,1,2.00,0.01,1615,428,310,1124331,930,43.00
4,1,2.00,1.00,2358,586,287,1165764,918,42.00
5,1,2.00,1.00,2358,586,287,1165764,825,42.00
6,1,3.00,0.01,2537,758,115,994427,864,43.00
7,1,0.01,0.01,555,332,306,1140573,554,40.00
8,1,1.00,0.01,555,332,306,1140573,830,43.00
9,1,1.00,0.01,555,332,306,1140573,940,43.00
10,1,1.00,0.01,555,332,306,1140573,918,43.00
11,1,0.01,0.01,555,332,306,1140573,918,43.00
12,1,0.01,0.01,555,332,306,1140573,864,43.00
13,1,3.00,1.00,2498,716,148,1281444,830,43.00
14,1,2.00,0.01,2498,716,148,1281444,830,43.00
15,1,2.00,0.01,2498,716,148,1281444,920,43.00
16,1,2.00,1.00,2498,716,148,1281444,360,40.00
17,1,2.00,0.01,2835,330,629,1124331,385,40.00
18,1,2.00,2.00,2835,330,629,1124331,918,43.00
19,1,3.00,0.01,1987,494,510,1369604,920,44.00
20,1,0.01,0.01,2057,307,621,1395924,792,43.00
21,1,0.01,0.01,2057,307,621,1395924,801,43.00
22,1,1.00,0.01,2057,307,621,1395924,573,41.00
23,1,1.00,0.01,2057,307,621,1395924,425,41.00
24,1,0.01,0.01,2057,307,621,1395924,801,43.00
25,1,1.00,0.01,2057,307,621,1395924,405,41.00
26,1,3.00,0.01,3207,145,467,1083455,509,53.00
27,1,2.00,0.01,474,212,492,1308645,554,38.00
28,1,2.00,0.01,1191,564,125,2068724,445,40.00
29,1,2.00,0.01,2536,817,156,1165764,360,40.00
...,...,...,...,...,...,...,...,...,...
1645,1,1.00,0.01,1565,702,44,1286868,904,75.00
1646,1,2.00,0.01,1565,702,44,1286868,904,75.00
1647,1,1.00,1.00,1565,702,44,1286868,920,75.00
1648,1,3.00,0.01,1565,702,44,1286868,904,75.00
1649,1,1.00,1.00,1565,702,44,1286868,864,75.00
1650,1,2.00,2.00,2650,419,381,1357174,842,17.00
1651,1,2.00,2.00,2650,419,381,1357174,554,14.00
1652,1,2.00,2.00,2650,419,381,1357174,484,14.00
1653,1,1.00,0.01,791,445,47,1056413,825,17.00
1654,1,4.00,3.00,2442,894,189,1783469,920,12.00
1655,1,2.00,2.00,2853,530,436,1915512,930,12.00
1656,1,1.00,0.01,1669,69,693,1447740,385,7.00
1657,1,1.00,0.01,1669,69,693,1447740,405,7.00
1658,1,1.00,0.01,1669,69,693,1447740,573,7.00
1659,1,1.00,0.01,1669,69,693,1447740,573,7.00
1660,1,1.00,0.01,1669,69,693,1447740,445,7.00
1661,1,1.00,0.01,1669,69,693,1447740,862,10.00
1662,1,3.00,2.00,2564,949,183,1803724,425,7.00
1663,1,2.00,2.00,2391,856,182,1395924,792,9.00
1664,1,1.00,0.01,1163,377,143,969501,509,6.00
1665,1,1.00,0.01,1163,377,143,969501,862,9.00
1666,1,2.00,0.01,1163,377,143,969501,445,6.00
1667,1,1.00,1.00,1163,377,143,969501,573,6.00
1668,1,2.00,2.00,604,542,106,1056413,360,5.00
1669,1,2.00,2.00,2866,562,416,1915512,554,2.00
1670,1,2.00,2.00,2866,562,416,1915512,360,2.00
1671,1,2.00,2.00,2488,1030,106,1395924,509,0.01
1672,1,2.00,2.00,2488,1030,106,1395924,509,0.01
1673,1,2.00,2.00,2488,1030,106,1395924,445,0.01
1674,1,2.00,2.00,2488,1030,106,1395924,445,0.01

In [22]:
model = sm.OLS(Y, X)
results = model.fit()

In [23]:
results.params

const         -549.359029
Quartos       -937.779373
Vagas          514.797631
DistIpanema     -0.347130
DistPraia       -0.894006
DistFavela       0.698976
RendaMedia       0.001592
Mes             14.368573
Idade           -7.396828
dtype: float64

In [24]:
predict = model.predict(results.params, X)

In [25]:
predict = pd.DataFrame(predict)

In [27]:
predict

                 0
0      4652.674888
1      5533.645541
2     11965.428906
3     11688.260549
4     11683.596809
5     10347.319516
6      8843.977543
7      8650.891540
8     11666.025638
9     13246.568672
10    12930.460065
11    13858.861645
12    13082.958700
13     9396.167304
14     9824.297023
15    11117.468597
16     3602.907830
17     3766.666017
18    12427.372252
19    10941.521396
20    12176.067867
21    12305.385025
22     8115.742447
23     5989.193636
24    12305.385025
25     5701.822176
26     4372.382740
27     7332.475579
28     6141.415077
29     2811.206714
...            ...
1645  11860.981960
1646  10923.202587
1647  12600.528783
1648   9985.423214
1649  11795.888693
1650  11709.661069
1651   7593.702516
1652   6587.902403
1653  11288.541019
1654  11698.623469
1655  13768.672022
1656   6146.217864
1657   6433.589325
1658   8847.509596
1659   8847.509596
1660   7008.332247
1661  12977.836723
1662   4982.676768
1663  10672.225297
1664   6689.838501
1665  11739.754302
1666   4832.470453
1667   8119.076830
1668   4802.018694
1669   8392.956439
1670   5605.453268
1671   6430.065804
1672   6430.065804
1673   5510.477129
1674   5510.477129

[1675 rows x 1 columns]

In [29]:
pd.DataFrame(Y)

      VAL_UNIT
0         4379
1         6479
2        12414
3        11250
4        13382
5        11618
6         6505
7         6410
8        14545
9        11111
10       19500
11       13636
12       20500
13       10135
14       10081
15       10508
16        4189
17        5313
18       11875
19       10610
20       16667
21       22667
22       14000
23        9333
24       18000
25        4500
26        3889
27        7759
28        4925
29        2593
...        ...
1645     13912
1646     12907
1647     14211
1648     13534
1649     13646
1650     13108
1651      6944
1652      7568
1653      5816
1654     13253
1655     13974
1656      6977
1657      3750
1658      7568
1659      6216
1660      7773
1661     15909
1662      5726
1663     13750
1664      5556
1665     13462
1666      7500
1667      8365
1668      2716
1669      8533
1670      4210
1671      4232
1672      6316
1673      6785
1674      6771

[1675 rows x 1 columns]